// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servibes.Appointments.Infrastructure;

namespace Servibes.Appointments.Infrastructure.Migrations
{
    [DbContext(typeof(AppointmentsContext))]
    partial class AppointmentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("appointments")
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Servibes.Appointments.Core.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_companyId")
                        .HasColumnName("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_reserveeId")
                        .HasColumnName("ReserveeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_status")
                        .IsRequired()
                        .HasColumnName("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Servibes.Appointments.Core.TimeReservations.TimeReservation", b =>
                {
                    b.Property<Guid>("TimeReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_companyId")
                        .HasColumnName("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("_employeeId")
                        .HasColumnName("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("_isCanceled")
                        .HasColumnName("IsCanceled")
                        .HasColumnType("bit");

                    b.HasKey("TimeReservationId");

                    b.ToTable("TimeReservations");
                });

            modelBuilder.Entity("Servibes.Appointments.Core.Appointments.Appointment", b =>
                {
                    b.OwnsOne("Servibes.Appointments.Core.Appointments.Employee", "_employee", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnName("EmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnName("EmployeeName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Servibes.Appointments.Core.Appointments.Service", "_service", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasColumnName("ServiceName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Price")
                                .HasColumnName("ServicePrice")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Servibes.Appointments.Core.Shared.ReservationDate", "_reservedDate", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("End")
                                .HasColumnName("End")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("Start")
                                .HasColumnName("Start")
                                .HasColumnType("datetime2");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });
                });

            modelBuilder.Entity("Servibes.Appointments.Core.TimeReservations.TimeReservation", b =>
                {
                    b.OwnsOne("Servibes.Appointments.Core.Shared.ReservationDate", "_reservedDate", b1 =>
                        {
                            b1.Property<Guid>("TimeReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("End")
                                .HasColumnName("End")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("Start")
                                .HasColumnName("Start")
                                .HasColumnType("datetime2");

                            b1.HasKey("TimeReservationId");

                            b1.ToTable("TimeReservations");

                            b1.WithOwner()
                                .HasForeignKey("TimeReservationId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
